apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp
 namespace: argoapp
spec:
 replicas: 2
 template:
  metadata:
    labels:
     app: argo-web
  spec: 
   containers:
   - name: c1
     image: quay.io/gauravkumar9130
     imagePullPolicy: Always
